config/urls.py
from django.contrib import admin
from django.urls import path
from product.views import home, product, products, statistics
from review.views import reviews
from service.views import services
from django.conf import settings
from django.conf.urls.static import static
from product import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home),
    path('products', products),    
    path('products/<int:id>/',product),  
    path("reviews",reviews),
    path('services',services),
    path("statistics", statistics)
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.db.models.signals import post_save,post_delete
from django.dispatch import receiver
from order.models import Order
from mptt.models import MPTTModel, TreeForeignKey
from django.db.models import F, Sum, ExpressionWrapper, FloatField

# Create your models here.

STATUS = (
    ('Не указано', 'Не указано'),
    ('Новый', 'Новый'),
    ('БУ', 'БУ')
)

class Category(MPTTModel):
    name = models.CharField("Названия",max_length=100)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        verbose_name = "категорию"
        verbose_name_plural = "Категории"
        ordering = ["name"]

class Product(models.Model):
    name = models.CharField("Названия",max_length=100)
    status = models.CharField('Статус', choices=STATUS, default='Не указано', max_length=15)
    category = TreeForeignKey(Category,on_delete=models.CASCADE, verbose_name="Категория", related_name="products")
    description = models.TextField("Описание", blank=True, null=True)
    price = models.PositiveSmallIntegerField('Цена продажи', default=0)    
    count = models.PositiveSmallIntegerField("Количество на текущий момент",default=0)
    total_count = models.PositiveBigIntegerField("Общая количество", default=0)
    average_price = models.FloatField("Средняя цена", default=0)
    in_stock = models.CharField("В наличии", default="Нет", max_length=3, choices=(("Да","Да"),("Нет","Нет")))
    created_at = models.DateTimeField("Дата",auto_now_add=True)
    amount_of_transaction = models.PositiveSmallIntegerField("Количество транзакций", default=0)
    is_published = models.CharField("Опубликовано", default="Нет", max_length=3, choices=(("Да","Да"),("Нет","Нет")))
    
    @property
    def invested(self):
        transactions = self.transaction_set.filter(action=Transaction.COMING)

        total_amount = transactions.annotate(
            total_price=ExpressionWrapper(F('count') * F('price'), output_field=FloatField())
        ).aggregate(
            total_amount=Sum('total_price'),
        )['total_amount']
        return total_amount - self.average_price * (self.total_count - self.count)

    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name"]

class ProductPhoto(models.Model):
    image = models.ImageField("Фотография",upload_to="product", blank=True, null=True)
    product = models.ForeignKey(Product,on_delete=models.CASCADE, verbose_name="Продукт")
    
    def __str__(self):
        return f"Фотография:{self.id} "

class Transaction(models.Model):
    COMING = "Приход"
    LEAVING = "Уход"
    ACTION = [
        (COMING,'Приход'),
        (LEAVING,'Уход'),
    ]
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    action = models.CharField("Действие",max_length=10, choices=ACTION)
    count = models.PositiveSmallIntegerField("Количество",default=0)
    price = models.FloatField("Цена")
    created_at = models.DateTimeField("Дата",auto_now_add=True)
    order = models.ForeignKey(Order,verbose_name="Заказ", on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return f"{self.action} {self.product.name}, количество: {self.count}, цена: {self.price}"

    def get_income(self):
        return self.price * self.count - self.product.average_price * self.count 

    class Meta:
        verbose_name = "транзакция"
        verbose_name_plural = "Транзакции"


def update_product_count(instance):
    product = instance.product
    #Пересчёт общего количества:  
    transactions = Transaction.objects.filter(product = product)
    
    product.average_price = 0
    product.count = 0 
    product.total_count = 0 
    product.amount_of_transaction = 0  
    for transaction in transactions:       
        
        if transaction.action == transaction.COMING:
            product.average_price += transaction.price * transaction.count 
            product.total_count += transaction.count
            product.count += transaction.count
            
        if transaction.action == transaction.LEAVING:
            product.count -= transaction.count
            product.amount_of_transaction += 1     

    product.average_price /= product.total_count 
    product.average_price = round(product.average_price) 
    if product.count > 0:
        product.in_stock = "Да"
    else:
        product.in_stock = "Нет"
        
    product.save() 
    
    


@receiver(post_save, sender=Transaction)
def update_product_total_count(sender, instance, **kwargs):    
    update_product_count(instance)
    
@receiver(post_delete, sender=Transaction)
def update_product_total_count_on_delete(sender, instance, **kwargs):
    update_product_count(instance)

service/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField("Названия",max_length=200)

    def __str__(self):
        return f"{self.title}"
    
    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "Категории"    


class Service(models.Model):
    title = models.CharField("Названия",max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    description = models.TextField("описание")
    image = models.ImageField("Фотография",upload_to="service", blank=True, null=True)
    price = models.PositiveSmallIntegerField("Цена")

    
    def __str__(self):
        return f"{self.title}"
    
    class Meta:
        verbose_name = "услуга"
        verbose_name_plural = "Сервисы" 

product/views.py
import math
from django.shortcuts import render
from django.core.paginator import Paginator
from django.db.models import F, Sum, ExpressionWrapper, Q, PositiveBigIntegerField
from datetime import datetime, timedelta

from .models import Product, Category, ProductPhoto, Transaction
from review.models import Review
from .utils.balance import get_balance


def home(request):  
    reviews = Review.objects.all() [:3]
    
    return render(request, "homepage.html",{"reviews": reviews})


def products(request):
    categories = Category.objects.all()
    products = Product.objects.filter(is_published = "Да", count__gt = 0)
    order = request.GET.get('order')          
    category = request.GET.get('category')          
    page = int(request.GET.get('page', 1))          

    if category:
        category = Category.objects.get(id=category)
        products = products.filter(category=category)
    
    total_products = len(products)
    count = 8
    pages = math.ceil(total_products / count)
    
    if order == "cheaper":        
        products = products.order_by('average_price') 

    elif order == "expensive":
        products = products.order_by('-average_price') 

    elif order == "new":
        products = products.order_by('-created_at')

    elif order == "popular":
        products = products.order_by('-amount_of_transaction')


    products = products[(page-1) * count : count * page]

    
    return render(
        request, 
        "products.html", 
        {
            "categories": categories, 
            'products': products, 
            'order': order, 
            'category': 
            category, 'pages': 
            range(1, pages+1), 
            'page': page
        }
    )


def product(request,id):
    product = Product.objects.get(id = id)
    images =  ProductPhoto.objects.filter(product = product)
    products = Product.objects.filter(is_published = "Да", count__gt = 0)[:12]

    return render(request, 'product.html', {"product": product, "images": images[1:], 'cover': images[0] if images else None, "products": products})


def services(request):
    return render(request, "services.html")

def statistics(request):
    month = request.GET.get('month')
    action = request.GET.get('action', 'Уход')
    # Общий фильтр по action и дате (если есть month)
    transaction_filter = Q(action=action)
    category_filter = Q(products__transaction__action=action)

    if month:
        start_date = datetime.strptime(month, "%m.%Y")
        end_date = (start_date + timedelta(days=32)).replace(day=1)
        transaction_filter &= Q(created_at__gte=start_date, created_at__lt=end_date)
        category_filter &= Q(products__transaction__created_at__gte=start_date, products__transaction__created_at__lt=end_date)

    # Общая сумма продаж за период
    total = Transaction.objects.filter(transaction_filter).aggregate(
        total=Sum(
            ExpressionWrapper(F('count') * F('price'), output_field=PositiveBigIntegerField())
        )
    )['total'] or 0

    # Продажи по категориям за период
    total_by_category = Category.objects.annotate(
        total_sales=Sum(
            ExpressionWrapper(
                F('products__transaction__count') * F('products__transaction__price'),
                output_field=PositiveBigIntegerField()
            ),
            filter=category_filter
        )
    ).order_by('-total_sales')

    total_by_category_top = total_by_category[:10]
    total_by_category_rest = sum(category.total_sales for category in total_by_category[10:] if category.total_sales)

    monthes = [date.strftime('%m.%Y') for date in Transaction.objects.dates('created_at', 'month', order='DESC')]

    products = Product.objects.filter(count__gt=0)
    total_invested_today = 0

    for p in products:
        p.invested_amount = p.invested
        total_invested_today += p.invested_amount

    sorted_products = sorted(products, key=lambda p: p.invested_amount, reverse=True)

    transactions = Transaction.objects.filter(action=Transaction.LEAVING)
    not_zero_transactions = []
    total_icnome = 0

    for t in transactions:
        t.income = t.get_income()
        total_icnome += t.income

    transactions = filter(lambda t: t.income != 0, transactions)
    transactions = sorted(transactions, key=lambda t: t.income, reverse=True)


    return render(
        request, 
        "statistics.html", 
        locals(),
    )
   
    
    
    

service/views.py
from django.shortcuts import render
from service.models import Category, Service
# Create your views here.

def services(request):
    categories = Category.objects.all()
    services = Service.objects.all()
    selected_category = request.GET.get("category")
    
    if selected_category:
        services = services.filter(category__id=selected_category)
        selected_category = int(selected_category)
    
    return render(
        request,
        "services.html", 
        {
            "services": services, 
            "categories": categories, 
            "selected_category": selected_category
        }
    )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} TechnoKB {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <script src="https://kit.fontawesome.com/0dac904ea8.js" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand fw-bold" href="/"><span class="text-danger">TECHNO</span>KB</a>

            <button class="navbar-toggler d-md-none btn-small" type="button" data-toggle="collapse"
                data-target="#navbar-collapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-md-flex justify-content-start" id="navbar-collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/products">Продукты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/services">Услуги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/reviews">Отзывы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/#adress">Адрес</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-danger px-3 text-white"
                            href="https://wa.me/+996553224265" target="_blank">Связаться</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    {% block body %}

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<header class="home-header text-white">
    <div class="home-header-container container py-3">
        <h2 class="small fw-bold text-danger h1">КОМПЬЮТЕРЫ, НОУТБУКИ, КОМПЛЕКТУЮЩИЕ, АКСЕССУАРЫ</h2>
        <h1 class="mb-3 fw-bold display-4">Компьютерный магазин<br>в Кара-Балта</h1>
        <p class="mb-4">Телефон: <a class="underline" href="tel:+96553224265">+96553224265</a></p>
        <a href="https://wa.me/+996553224265" target="_blank" class="btn btn-outline-danger">Связаться</a>
        <a href="/products" class="btn btn-danger">Ассортимент</a>
    </div>
    <img class="home-header-bg" src="{% static 'img/bg.png' %}" alt="">
</header>
<section class="main-adventages my-3">
    <div class="container py-5 row text-secondary text-center justify-content-between mx-auto">
        <h2 class="d-none">Преимущества</h2>
        <div class="m-2 bg-light p-2 d-flex flex-column justify-content-center align-items-center col-lg-2 col-md-4">
            <i class="fa-solid fa-arrow-down fa-3x"></i>
            <h3 class="mt-3">ЦЕНЫ</h3>
        </div>
        <div class="m-2 bg-light p-2  d-flex flex-column justify-content-center align-items-center col-lg-2 col-md-4">
            <i class="fas fa-shield-alt fa-3x"></i>
            <h3 class="mt-3">ГАРАНТИЯ</h3>
        </div>
        <div class="m-2 bg-light p-2  d-flex flex-column justify-content-center align-items-center col-lg-2 col-md-4">
            <i class="fas fa-shipping-fast fa-3x"></i>
            <h3 class="mt-3">ДОСТАВКА<br>ПО КР</h3>
        </div>
        <div class="m-2 bg-light p-2  d-flex flex-column justify-content-center align-items-center col-lg-2 col-md-4">
            <i class="fas fa-exchange-alt fa-3x"></i>
            <h3 class="mt-3">ТРЕЙД ИН</h3>
        </div>
    </div>
</section>
<section class="reviews container py-5">
    <h2 class="text-center mb-4">Наши клиенты довольны нашей техникой</h2>
    <div class="row reviews-container">
        {% for review in reviews %}

        <div class=" py-2 col-4 col-lg-4 col-md-12">
            <div class="card p-3">
                <div class="d-flex justify-content-between">
                    <div class="d-flex">
                        <img src="https://via.placeholder.com/50" class="rounded-circle me-3" alt="Avatar">
                        <div>
                            <h3 class="mb-1 fw-semibold h6">{{review.client}}</h3>
                            <small class="text-muted">+996 (553) 224 2**</small>
                        </div>
                    </div>
                    <div class="d-flex align-items-center">
                        <i class="bi bi-star-fill star-icon me-1"></i>
                        <span class="fw-bold">{{review.raiting}}</span>
                    </div>
                </div>
                <p class="mt-3 mb-0 text-secondary">
                    {{review.comment}}
                </p>
            </div>
        </div>
        {% endfor %}

    </div>
</section>

<section class="py-5 container" id="adress">
    <h2>Мы находимся в Кара-Балта</h2>
    <p>Карла Маркса 21, 2 этаж</p>
    <div class="bg-secondary" style="height: 20vh">
        <iframe
            src="https://yandex.ru/map-widget/v1/?um=constructor%3Acf2f97d890032d5835727698a1acaeea37640c1c7d38bfe1d4f510d211d1b630&amp;source=constructor"
            width="100%" height="100%" frameborder="0"></iframe>
    </div>
</section>
<section class="license bg-light text-center py-5">
    <div class="container">
        <h2 class="mb-4">Свидетельство<br><small>о государственной регистрации</small></h2>
        <a class="btn btn-outline-danger btn-small" href="">Просмотр</a>

    </div>
</section>
<footer class="footer bg-dark text-white text-center p-1">
    <div class="container">
        TecnoKB
    </div>
</footer>
<!-- <div class="container">
    <h1>Главная страница</h1>
    {% for category in categories %}
    <a href="/products?category={{ category.id }}">{{category.name}}</a>
    {% endfor %}
</div> -->
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load static %}


{% block title %}TechnoKB - {{product.name}} {% endblock %}
{% block body %}
<div class="container py-5">

    <div>
        <p>
            <a href="Продукты">Продукты</a>
            {% for parent in product.category.get_ancestors %}
            / {{ parent.name }}
            {% endfor %}
            / <a href="/products?category={{product.category.id}}">{{product.category.name}}</a>
        </p>
    </div>
    <h1>{{product.name}}</h1>
    <p class="text-secondary small">В наличии: {{product.count}} шт</p>
    {% if cover %}
    <div class="product-cover bg-dark product-cover-full">
        <img class="product-cover-img" src="{{cover.image.url}}" alt="">
    </div>
    {% endif %}


    {% for image in images %}
    <img src="{{ image.image.url }}" alt="{{ product.name }}" width="200px">
    {% endfor %}

    <p class="text-pre-wrap mt-4">{{product.description}}</p>
    <hr>
    <h2 class="h4">Дополнительно: </h2>
    <ul>
        <li>📍 Адрес: <a href="/#adress" class="text-danger">Кара-Балта, Карла Маркса 21</a></li>
        <li>✅ 14 дней гарантия</li>
        <li>🚚 Доставка по Кыргызстану</li>
        <li>💰 Скидки при оптовых покупках</li>
        <li>📝 Система лояльности для постоянных клиентов</li>
    </ul>

    <h2 class="h4 mt-5">Смотрите похожее</h2>

    <!-- <div class="row">
        {% for product in products %}
        <div class="col-3 p-1">
            <a href="/products/{{product.id}}" class="card">
                <div class="card-img-top rectangle bg-dark"></div>
                <div class="card-body">
                    <h3 class="card-title text-danger mb-0 fw-bold">16 000 сом</h3>
                    <small class="text-secondary">{{product.category.name}}</small>
                    <p class="mt-2">{{product.name}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div> -->

</div>
{% endblock %}

templates/products.html
{% extends 'base.html' %}
{% load mptt_tags %}


{% load static %}

{% block body %}

<div class="container my-5">
    <h2>Категории</h2>
    {% if category %}
    <p class="mb-0">Выбранная категория: <span class="text-danger">{{category}}</span> <a
            href="/products{% if order %}?order={{order}}{% endif %}" class="underline"><small>(сбросить)</small></a>
    </p>
    {% endif %}

    <ul class="mt-2">
        {% recursetree categories %}
        <li>
            {% if not node.is_leaf_node %}
            <details class="{% if node.name == 'Услуги'%}d-none{% endif %}">
                <summary>{{ node.name }}</summary>
                <ul>
                    {{ children }}
                </ul>
            </details>
            {% else %}
            <a href="?category={{node.id}}{% if order %}&order={{order}}{% endif %}">{{ node.name }}</a>
            {% endif %}
        </li>
        {% endrecursetree %}
    </ul>

</div>

{% if products|length > 1 %}

<div class="container my-5">
    <div class="d-flex justify-content-between align-items-center">
        <h2>Товары</h2>
        <form method="GET">
            <input type="text" name="category" id="" value="{% if category %}{{category.id}}{% endif %}" hidden>

            <select class="form-control" name="order" onchange="this.form.submit()">
                <option value="default">По умолчанию</option>
                <option value="popular" {% if order == "popular" %}selected{% endif %}>Популярные</option>
                <option value="new" {% if order == "new" %}selected{% endif %}>Сначала новые</option>
                <option value="cheaper" {% if order == "cheaper" %}selected{% endif %}>Сначала дешевле</option>
                <option value="expensive" {% if order == "expensive" %}selected{% endif %}>Сначала дороже</option>
            </select>
        </form>

    </div>

    <div class="row">
        {% for product in products %}
        <div class="col-lg-4 col-md-6 col-sm-12 p-1">
            <a href="/products/{{product.id}}" class="card">
                <div class="card-img-top bg-dark product-cover">
                    {% with product.productphoto_set.all|first as first_photo %}
                        <img 
                            class="product-cover-img" 
                            src="{% if first_photo.image %}
                                    {{ first_photo.image.url }}
                                    {% else %} {% static 'img/product-default-cover.png' %}
                                {% endif %}" 
                            alt="{{ product.name }}"
                        >
                    {% endwith %}
                </div>

                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <small class="text-secondary">{{product.category.name}}</small>
                        <h3 class="card-title btn btn-warning mb-0 fw-bold">{{ product.price }} сом</h3>
                    </div>
                    <p class="mt-2">{{product.name}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="container my-5">
        <h2>
            {% if category %}
            Товаров в данной категории нет,<br>попробуйте другую
            {% else %}
            Товары не доступны на данный момент
            {% endif %}
        </h2>
    </div>

    {% endif %}
    {% if pages|length > 1 %}
    <div class="container my-5 text-center">
        {% for i in pages %}
        <a class="mx-1 {% if i == page %}text-danger{% endif %}"
            href="?page={{i}}{% if category %}&category={{category.id}}{% endif %}">{{i}}</a>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

templates/reviews.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<section class="reviews container py-5">
   <h2 class="text-center mb-4">Наши клиенты довольны нашей техникой</h2>
   <div class="row reviews-container">
      {% for review in reviews %}

      <div class=" py-1 col-4 col-md-12">
         <div class="card p-2">
            <div class="d-flex justify-content-between">
               <div class="d-flex">
                  <img src="https://via.placeholder.com/50" class="rounded-circle me-3" alt="Avatar">
                  <div>
                     <h3 class="mb-1 fw-semibold h6">{{review.client}}</h3>
                     <small class="text-muted">+996 (553) 224 2**</small>
                  </div>
               </div>
               <div class="d-flex align-items-center">
                  <i class="bi bi-star-fill star-icon me-1"></i>
                  <span class="fw-bold">{{review.raiting}}</span>
               </div>
            </div>
            <p class="mt-3 mb-0 text-secondary">
               {{review.comment}}
            </p>
         </div>
      </div>
      {% endfor %}

   </div>
</section>








{% endblock %}

templates/services.html
{% extends 'base.html' %}
{% load mptt_tags %}


{% load static %}

{% block body %}
<div class="container my-5">
    <h1 class="text-center mb-4 h2">Ремонт, настройка и обслуживание</h1>
    <div class="my-2">
        {% for category in categories %}
        <a class="btn mr-2 mb-2 {% if category.id == selected_category %}btn-danger {% else %}btn-light{% endif %}"
            href="?category={{category.id}}">{{category}}</a>
        {% endfor %}
    </div>
    {% for service in services %}

    <div class="card p-2">
        <div class="row justify-content-between card-body">
            <div class="col-6 bg-dark p-0" style="height: 300px;">
                {% if service.image %}
                    <img class="w-100 h-100 service__image" src="{{service.image.url}}" alt="">
                {% endif %}
            </div>
            <div class="col-6  ps-4">
                <h2 class="h4">{{service.title}}</h2>
                <p class="text-secondary"><small>{{service.category}}</small></p>
                <p>{{service.description}}</p>
                <p class="btn btn-warning">{{service.price}} сом</p>
            </div>

        </div>
    </div>
    {% endfor %}


</div>

<!-- {% for service in services %}
            <p>{{service.title}}</p>
            <p>{{service.category}}</p>
            <p>{{service.description}}</p>
            <p>{{service.price}}</p>
        {% endfor %} -->


{% endblock %}